// Code generated by "stringer -type=Type -output=file_types_string.go"; DO NOT EDIT.

package batches

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JAVA_PROPERTIES-1]
	_ = x[IOS-2]
	_ = x[STRINGSDICT-3]
	_ = x[ANDROID-4]
	_ = x[GETTEXT-5]
	_ = x[PHP_RESOURCE-6]
	_ = x[RESX-7]
	_ = x[XLIFF-8]
	_ = x[YAML-9]
	_ = x[JSON-10]
	_ = x[XML-11]
	_ = x[HTML-12]
	_ = x[FREEMARKER-13]
	_ = x[DOCX-14]
	_ = x[PPTX-15]
	_ = x[XLSX-16]
	_ = x[IDML-17]
	_ = x[XLS-18]
	_ = x[DOC-19]
	_ = x[QT-20]
	_ = x[CSV-21]
	_ = x[TMX-22]
	_ = x[PLAIN_TEXT-23]
	_ = x[PPT-24]
	_ = x[PRES-25]
	_ = x[MADCAP-26]
	_ = x[SRT-27]
	_ = x[MARKDOWN-28]
	_ = x[DITA-29]
	_ = x[DITA_ZIP-30]
	_ = x[VTT-31]
	_ = x[PDF-32]
	_ = x[RTF-33]
	_ = x[FLARE-34]
	_ = x[FLUENT-35]
	_ = x[SVG-36]
	_ = x[DOCM-37]
	_ = x[ARB-38]
	_ = x[INDD-39]
	_ = x[XCSTRINGS-40]
	_ = x[VSDX-41]
	_ = x[VSDM-42]
}

const _Type_name = "JAVA_PROPERTIESIOSSTRINGSDICTANDROIDGETTEXTPHP_RESOURCERESXXLIFFYAMLJSONXMLHTMLFREEMARKERDOCXPPTXXLSXIDMLXLSDOCQTCSVTMXPLAIN_TEXTPPTPRESMADCAPSRTMARKDOWNDITADITA_ZIPVTTPDFRTFFLAREFLUENTSVGDOCMARBINDDXCSTRINGSVSDXVSDM"

var _Type_index = [...]uint8{0, 15, 18, 29, 36, 43, 55, 59, 64, 68, 72, 75, 79, 89, 93, 97, 101, 105, 108, 111, 113, 116, 119, 129, 132, 136, 142, 145, 153, 157, 165, 168, 171, 174, 179, 185, 188, 192, 195, 199, 208, 212, 216}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
