// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package mt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DOCX-1]
	_ = x[DOCM-2]
	_ = x[RTF-3]
	_ = x[PPTX-4]
	_ = x[XLSX-5]
	_ = x[IDML-6]
	_ = x[RESX-7]
	_ = x[PLAIN_TEXT-8]
	_ = x[XML-9]
	_ = x[HTML-10]
	_ = x[PRES-11]
	_ = x[SRT-12]
	_ = x[MARKDOWN-13]
	_ = x[DITA-14]
	_ = x[VTT-15]
	_ = x[FLARE-16]
	_ = x[SVG-17]
	_ = x[XLIFF2-18]
	_ = x[CSV-19]
	_ = x[JSON-20]
	_ = x[XLSX_TEMPLATE-21]
}

const _FileType_name = "DOCXDOCMRTFPPTXXLSXIDMLRESXPLAIN_TEXTXMLHTMLPRESSRTMARKDOWNDITAVTTFLARESVGXLIFF2CSVJSONXLSX_TEMPLATE"

var _FileType_index = [...]uint8{0, 4, 8, 11, 15, 19, 23, 27, 37, 40, 44, 48, 51, 59, 63, 66, 71, 74, 80, 83, 87, 100}

func (i FileType) String() string {
	i -= 1
	if i < 0 || i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
